### ISSUE TITLE
ZSM42 generation different rel file from ZSM41. Linker generates empty file.

### ISSUE THREAD

**Issue by b1ackmai1er** [hperaza/ZSM4#1]
HI Hector, 

Was updating the copy of ZSM from 41 to 42 in the ROMWBW distribution but on checking, the final .BIN file for the forth rom after linking was all 0's. There are no errors generated from assemble but rel files are slightly different. Linker is DR LINK 1.31. No changes to build process. REL files attached.

This is the link to directory for the files being assembled with ZSM 

https://github.com/wwarthen/RomWBW/tree/dev/Source/Forth

The file in particular is camel80,azm which uses .phase/.dephase

The build code is

zx zsm =camel80.azm -/l
zx link -CAMEL80.BIN=CAMEL80

[Forth.zip](https://github.com/hperaza/ZSM4/files/5822052/Forth.zip)

Link output from 41
LINK 1.31

ABSOLUTE     0000
CODE SIZE    1700 (0100-17FF)
DATA SIZE    0000
COMMON SIZE  0000
USE FACTOR     00

Link output from 42
LINK 1.31

ABSOLUTE     16B5 (0000-16B4)
CODE SIZE    1700 (0100-17FF)
DATA SIZE    0000
COMMON SIZE  0000
USE FACTOR     00

Please let me know if you need any more information.

Regards Phil

**Comment by b1ackmai1er** [comment]
Hi Hector,

I resolved my issues by adding CSEG prior to my .phase statements and specifying a load parameter in the DR Link80. i.e.

	CSEG
	.PHASE	FTH_LOC
	.... code
	.DEPHASE

from: zx link -CAMEL80.BIN=CAMEL80
to: zx link -CAMEL80.BIN[L200]=CAMEL80

Is this the correct behavior and the old behavior incorrect? Your change notes seem to imply this but I am sure.

Thanks.

**Comment by hperaza** [comment]
Hi Phil,

Sorry for not answering earlier, for some reason GitHub is not sending me notifications about Issues.

I just uploaded a fix for the .PHASE problem; the bug was introduced by the code that tried to keep L80 happy, and now CAMEL80 compiles and links properly.

Let me know if it works for you.

Best regards,
Hector.

**Comment by b1ackmai1er** [comment]
Thanks Hector, testing an updating romwbw now.

Best Wishes Phil

**Comment by b1ackmai1er** [comment]
Thanks Hector, all seems to be fine.
