### ISSUE TITLE
Instruction LD I,A flagged as error when using /U option

### ISSUE THREAD

**Issue by tlink2000** [hperaza/ZSM4#2]
I have Z80 code containing the "LD I,A" instruction.  The instruction generates an "O" error when I specify the /U (undefined symbols) option to ZSM4 but compiles correctly if I leave that option off.  See below:

![image](https://user-images.githubusercontent.com/38814273/105044747-165ea500-5a35-11eb-87aa-c5be528d9f99.png)

**Comment by hperaza** [comment]
Thanks for the report. Fixed in version 4.3, just uploaded.
