### ISSUE TITLE
Problem in the INT routine from EVAL.MAC

### ISSUE THREAD

**Issue by Laci1953** [hperaza/ZSM4#3]
It seems to me that the INT routine does not parse correctly the string of characters, enabling some annoying errors to escape unnoticed.

Example: the line:

 ld hl,1v2

is assembled as:
  0000' 21 00FC                  ld hl,1v2

,without indicating the obvious syntax error: 1v2 is not a valid number! and 0FCH is not the correct value !

This way, you risk assembling a source containing such syntax errors without being warned about these errors!

**Comment by Laci1953** [comment]
I fixed-it.
The corrected INT routine:

;
;	INT - Convert characters to binary
;
;	Allow trailing 'H' for hex, 'O' or 'Q' for octal, 'D' for decimal
;	and 'B' for binary. Default base is the current .RADIX setting.
;
INT:	ld	hl,(RADIX)
	ld	(BASE),hl	; set up default base
	ld	b,0		; set up length counter
	call	GNC		; skip blanks
	ld	hl,(PTR1)
	dec	hl		; HL = begin of string
	push	hl		; save pointer
INT1:	cp	'0'
	jr	c,INT3		; exit loop if terminator
	cp	'9'+1
	jr	c,INT2
	cp	'A'
	jr	c,INT3
	cp	'Z'+1
	jr	nc,INT3
INT2:	inc	hl
	ld	a,(hl)		; get next character
	call	UCASE
	inc	b
	jr	INT1		; increment counter and continue loop
;
INT3:	ld	(PTR1),hl
	dec	hl
	ld	a,(hl)
	call	UCASE
	cp	'H'
	ld	hl,16		; base 16
	ld	ix,HexVerif
	jr	z,INT4		; branch if hex
	cp	'D'
	ld	hl,10		; base 10
	ld	ix,DecVerif
	jr	z,INT4		; branch if decimal
	cp	'Q'
	ld	hl,8		; base 8
	ld	ix,OctVerif
	jr	z,INT4		; branch if octal
	cp	'O'
	jr	z,INT4		; branch if octal
	cp	'B'
	ld	hl,2		; base 2
	ld	ix,DecVerif
	jr	nz,INT5		; branch if not binary
	ld	ix,BinVerif
INT4:	dec	b		; decrement counter
	ld	(BASE),hl	; set up base
INT5:	ld	de,0		; set up accumulator
INT6:	pop	hl		; get saved pointer to string
	ld	a,(hl)
	inc	hl
	push	hl
	call	UCASE
	ld	hl,return
	push	hl
	jp	(ix)		;check char
return:	jr	nc,usechar
				;check failed
	pop	hl		;drop pointer to string
	pop	hl		;drop ret addr
	ld	hl,0
	ld	(INTBUF),hl	;set value=0
	jp	EXPERR
usechar:
	push	af		; get binary value of this digit
	ld	hl,(BASE)
	call	MULT
	pop	af
	ld	e,a
	ld	d,0
	add	hl,de		; add in new digit
	ex	de,hl
	djnz	INT6		; go back if more to do
	pop	hl		; drop pointer to string
	ex	de,hl
	ld	(INTBUF),hl	; save value
	ret
;
;	Validation of current char, in the given base
;	returns CARRY=1 : not valid
;		CARRY=0 : valid, value in A
;
BinVerif:
	cp	'0'
	jr	z,Ok
	cp	'1'
	jr	z,Ok
	scf
	ret
Ok:
	sub	'0'		;CARRY=0
	ret
OctVerif:
	cp	'0'
	ret	c
	cp	'8'
	jr	c,Ok
	scf
	ret
DecVerif:
	cp	'0'
	ret	c
	cp	'9'+1
	jr	c,Ok
Bad:
	scf
	ret
HexVerif:
	cp	'0'
	ret	c
	cp	'9'+1
	jr	c,Ok
	cp	'A'
	ret	c
	cp	'F'+1
	jr	nc,Bad
	sub	'A'-10		;CARRY=0
	ret
;

**Comment by hperaza** [comment]
Thanks, fixed.
